%macro m_import_type(start,end,type,input,outdata);
%do I=&start %to &end %by 1;
data _null_;
	set bdlref.url;
	if year = &I then do;
		call symputx('url_ref',url);
		call symputx('id',league_id);
		end;
run;
data _null_;
	set bdlref.xml_map;
		if program = "&type" then do;
			call symputx('map',map_file);
			end;
run;
%put &map;
%if &type = players %then %do;
data _null_;
	call symputx('Url',CATX('.',"http://www&url_ref","myfantasyleague","com/&I/export?TYPE=&type&DETAILS=1&L=&id&W=YTD&JSON=0"));
run;
%end;
%if &type ne players %then %do;
data _null_;
	call symputx('Url',CATX('.',"http://www&url_ref","myfantasyleague","com/&I/export?TYPE=&type&L=&id&W=YTD&JSON=0"));
run;
%end;
%put &url;

filename  output URL "&url";
filename  SXLEMAP "/home/cwillis/BDL/data/xml_maps/&map";
libname   output xmlv2 xmlmap=SXLEMAP access=READONLY;
DATA &outdata&&I; 
	SET output.&input;
	year=&I;
run;
%end;
%mend m_import_type;
