%macro m_import_adp(start,end);
%do i=&start %to &end %by 1;
data _null_;
	set ref.url;
	if year = &i then do;
		call symputx('url_ref',url);
		call symputx('id',league_id);
		end;
run;

data _null_;
	set ref.xml_map;
	if program = 'adp' then do;
			call symputx('map',map_file);
			end;
run;
%put &map;
data _null_;
	call symputx('Url',CATX('.',"http://www&url_ref","myfantasyleague","com/&i/export?TYPE=adp&L=&IS_MOCK=0&IS_PPR=0&JSON=0"));
run;
%put &url;
filename  output URL "&Url";
filename  SXLEMAP "/folders/myfolders/cwillis/Data/Import/XML_Maps/&map";
libname   output xmlv2 xmlmap=SXLEMAP access=READONLY;
DATA adp_&i; 
	SET output.player;
		year="&i";
run;
%end;
%mend m_import_adp;
